sudo: required
services:
  - docker

before_install:
  - docker build -t eduardozenardi/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script:
  - docker run eduardozenardi/react-test npm test  -- --coverage

after_success:
  - docker build -t eduardozenardi/multi-client ./client
  - docker build -t eduardozenardi/multi-nginx ./nginx
  - docker build -t eduardozenardi/multi-server ./server
  - docker build -t eduardozenardi/multi-worker ./worker

  #Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push eduardozenardi/multi-client
  - docker push eduardozenardi/multi-nginx
  - docker push eduardozenardi/multi-server
  - docker push eduardozenardi/multi-worker
  